apiVersion: v1
kind: pod
metadata:
  name: nginx-demo
  label:
    type: app
    version: v1
  namespace: 'default'
spec:
  containers:
    - name: nginx
      image: nginx:1.7.9
      imagePullPolicy: IfNotPresent
      command:
        - nginx
        - -g
        - 'daemon off'
      workingDir: /usr/share/nginx/html
      ports:
        - name: http
          containerPort: 80
          protocol: TCP
        - env:
          name: JVM_OPTS
          value: '-Xms128m -Xmx128m'

      resources:
        requests:
          cpu: 100m
          memory: 128Mi
        limits:
          cpu: 200m
          memory: 250Mi
  restartPolicy: OnFailed